server:
  address: 0.0.0.0
  port: 8080
  servlet:
    contextPath: /

  error:
    whitelabel:
      enabled: false

  compression:
    enabled: true
    min-response-size: 256
    mime-types: text/html,text/xml,text/plain,application/json,application/xml,text/css,application/javascript,image/svg+xml

spring:
  application:
    name: main-service

  ## enabling overriding by setting spring.main.allow-bean-definition-overriding=true
  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true      
      show_sql: false
      format_sql: false
      ## none, validate, update, create, create-drop  
      ddl-auto: none 
    show-sql: false
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
      fail-on-empty-beans: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp    

  servlet:
    multipart:
      enabled: true
      max-file-size: 31MB
      max-request-size: 31MB

  batch:
    table-prefix: batch_
    job:
      enabled: false
    # always, never
    initialize-schema: never  
    initializer:
      enabled: false

  # RabbitMQ properties
#  rabbitmq:
#   addresses: localhost:5672
#   adminAddresses: http://localhost:15672
#   nodes: rabbit@localhost
#   username: guest
#   password: guest
#   virtual-host: /
#   useSSL: false
#   sslProperties:
#   ssl:
#     keyStore:
#     keyStorePassphrase:
#     trustStore:
#     trustStorePassphrase:
#   channelCacheSize: 100
#   listener:
#     simple:
#       default-requeue-rejected: false
#       retry:
#         enabled: true
#       # auto, manual
#       acknowledge-mode: auto


security:
  basic:
    enabled: false

logging:
  file: app.log
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  level:
    tw.com.firstbank: DEBUG
#    org.hibernate.SQL: DEBUG
    org.springframework: DEBUG
#    org.springframework.http.client: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

jasypt:
  encryptor:
    algorithm: PBEWITHMD5ANDTRIPLEDES
    password: 123qweAS

opentracing:
  jaeger:
    enabled: true
    log-spans: true  
    service-name: ${spring.application.name}
    udp-sender:
      host: 10.106.220.158
      port: 6831
    #http-sender:
    #  url: http://jaegerhost:portNumber/api/traces
    const-sampler:
      decision: true

#springfox:
#  documentation:
#    open-api:
#      v3:
#        path: /api-docs

feature:
  main-service: true
      

